# Generated by Django 3.0.3 on 2020-02-26 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_description_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='description',
            name='content',
            field=models.TextField(),
        ),
    ]
